#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'git',     github: 'fnichol/chef-git'
cookbook 'curl',    github: 'phlipper/chef-curl'
cookbook 'locale'
# cookbook 'imagemagick'
# cookbook 'xvfb',    github: 'u2i/chef-xvfb'
# cookbook 'firefox', github: 'substantial/cookbook-firefox'
cookbook 'elasticsearch'
cookbook 'java'
cookbook 'memcached'
cookbook 'ulimit',  github: 'bmhatfield/chef-ulimit' # dependency of redisio

# Manage ruby installations
# cookbook 'rvm', github: 'fnichol/chef-rvm', ref: 'v0.9.0'

# Database
cookbook 'postgresql', github: 'phlipper/chef-postgresql', ref: '0.14.1'
cookbook 'redisio', github: 'brianbianco/redisio'